"""initial_schema

Revision ID: 607b4c53997b
Revises: 
Create Date: 2026-05-09 00:25:40.958837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607b4c53997b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id_organizacion', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('plan_suscripcion', sa.String(length=50), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("plan_suscripcion IN ('basico', 'profesional', 'empresarial')", name='ck_organizaciones_plan_suscripcion'),
    sa.PrimaryKeyConstraint('id_organizacion')
    )
    op.create_index(op.f('ix_organizaciones_deleted_at'), 'organizaciones', ['deleted_at'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_organizacion', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=254), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('token_api_hash', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rol IN ('admin', 'operador', 'auditor')", name='ck_usuarios_rol'),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizaciones.id_organizacion'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_deleted_at'), 'usuarios', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_usuarios_id_organizacion'), 'usuarios', ['id_organizacion'], unique=False)
    op.create_table('comprobantes',
    sa.Column('id_comprobante', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('imagen_path', sa.String(length=500), nullable=False),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fecha_deposito', sa.Date(), nullable=True),
    sa.Column('numero_operacion', sa.String(length=100), nullable=True),
    sa.Column('banco', sa.String(length=50), nullable=True),
    sa.Column('hash_documento', sa.String(length=64), nullable=False),
    sa.Column('estado_actual', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado_actual IN ('recibido', 'procesando', 'comparando', 'en_revision', 'valido', 'duplicado', 'error')", name='ck_comprobantes_estado_actual'),
    sa.CheckConstraint('monto IS NULL OR monto >= 0', name='ck_comprobantes_monto_no_negativo'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_comprobante'),
    sa.UniqueConstraint('hash_documento')
    )
    op.create_index(op.f('ix_comprobantes_deleted_at'), 'comprobantes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comprobantes_estado_actual'), 'comprobantes', ['estado_actual'], unique=False)
    op.create_index(op.f('ix_comprobantes_fecha_deposito'), 'comprobantes', ['fecha_deposito'], unique=False)
    op.create_index(op.f('ix_comprobantes_id_usuario'), 'comprobantes', ['id_usuario'], unique=False)
    op.create_table('log_procesamiento',
    sa.Column('id_log', sa.Uuid(), nullable=False),
    sa.Column('id_comprobante', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('etapa', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("nivel IN ('INFO', 'WARN', 'ERROR')", name='ck_log_procesamiento_nivel'),
    sa.ForeignKeyConstraint(['id_comprobante'], ['comprobantes.id_comprobante'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_log_procesamiento_etapa'), 'log_procesamiento', ['etapa'], unique=False)
    op.create_index(op.f('ix_log_procesamiento_id_comprobante'), 'log_procesamiento', ['id_comprobante'], unique=False)
    op.create_index(op.f('ix_log_procesamiento_nivel'), 'log_procesamiento', ['nivel'], unique=False)
    op.create_table('validaciones',
    sa.Column('id_validacion', sa.Uuid(), nullable=False),
    sa.Column('id_comprobante', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=True),
    sa.Column('score_similitud', sa.Float(), nullable=True),
    sa.Column('clasificacion', sa.String(length=20), nullable=False),
    sa.Column('metodo_deteccion', sa.String(length=30), nullable=False),
    sa.Column('fecha_validacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("clasificacion IN ('valido', 'sospechoso', 'duplicado')", name='ck_validaciones_clasificacion'),
    sa.CheckConstraint("metodo_deteccion IN ('hash_exacto', 'campos_exactos', 'scoring_ponderado', 'manual')", name='ck_validaciones_metodo_deteccion'),
    sa.CheckConstraint('score_similitud IS NULL OR (score_similitud >= 0 AND score_similitud <= 1)', name='ck_validaciones_score_rango'),
    sa.ForeignKeyConstraint(['id_comprobante'], ['comprobantes.id_comprobante'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_validacion')
    )
    op.create_index(op.f('ix_validaciones_deleted_at'), 'validaciones', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_validaciones_id_comprobante'), 'validaciones', ['id_comprobante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validaciones_id_comprobante'), table_name='validaciones')
    op.drop_index(op.f('ix_validaciones_deleted_at'), table_name='validaciones')
    op.drop_table('validaciones')
    op.drop_index(op.f('ix_log_procesamiento_nivel'), table_name='log_procesamiento')
    op.drop_index(op.f('ix_log_procesamiento_id_comprobante'), table_name='log_procesamiento')
    op.drop_index(op.f('ix_log_procesamiento_etapa'), table_name='log_procesamiento')
    op.drop_table('log_procesamiento')
    op.drop_index(op.f('ix_comprobantes_id_usuario'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_fecha_deposito'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_estado_actual'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_deleted_at'), table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index(op.f('ix_usuarios_id_organizacion'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_deleted_at'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_organizaciones_deleted_at'), table_name='organizaciones')
    op.drop_table('organizaciones')
    # ### end Alembic commands ###
